version: "3.9"
services:
  db:
    image: mysql:8.2
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
      - --default-time-zone=Asia/Tokyo
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./tmp/db:/var/lib/mysql
      - ./backend/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: change_me_right_now
      TZ: Asia/Tokyo
  backend:
    build: 
      context: ./backend
      dockerfile: development.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  bundle_cache:
